[brew]
  aom = "3.13.1"
  asciinema = "3.0.1"
  bartib = "1.1.0"
  bash = "5.3.3"
  "bash-completion@2" = "2.17.0"
  bat = "0.26.0"
  bfg = "1.15.0"
  brew-file = "10.1.2"
  brotli = "1.2.0"
  c-ares = "1.34.5"
  ca-certificates = "2025-11-04"
  cairo = "1.18.4"
  certifi = "2025.10.5_1"
  chezmoi = "2.67.0"
  cmake = "4.1.2"
  dos2unix = "7.5.3"
  fastfetch = "2.54.0_1"
  fontconfig = "2.17.1"
  freetype = "2.14.1_1"
  fzf = "0.66.1"
  gawk = "5.3.1"
  gettext = "0.26_1"
  gh = "2.83.0"
  giflib = "5.2.2"
  git-filter-repo = "2.47.0"
  glib = "2.86.1"
  gmp = "6.3.0"
  gnu-getopt = "2.41.2"
  gnu-sed = "4.9"
  gnupg = "2.4.8"
  gnutls = "3.8.10"
  go = "1.25.4"
  graphite2 = "1.3.14"
  harfbuzz = "12.2.0"
  highway = "1.3.0"
  "icu4c@77" = "77.1"
  imagemagick = "7.1.2-8_1"
  imath = "3.2.2"
  jasper = "4.2.8"
  jpeg-turbo = "3.1.2"
  jpeg-xl = "0.11.1_3"
  kanata = "1.9.0"
  keychain = "2.9.8"
  lftp = "4.9.3"
  libassuan = "3.0.2"
  libde265 = "1.0.16"
  libdeflate = "1.25"
  libevent = "2.1.12_1"
  libgcrypt = "1.11.2"
  libgit2 = "1.9.1"
  libgpg-error = "1.56"
  libheif = "1.20.2"
  libidn2 = "2.3.8"
  libksba = "1.6.7"
  liblinear = "2.49"
  liblqr = "0.4.3"
  libmaxminddb = "1.12.2"
  libnghttp2 = "1.68.0"
  libnghttp3 = "1.12.0"
  libomp = "21.1.5"
  libpng = "1.6.50"
  libraw = "0.21.4"
  libsmi = "0.5.0"
  libsodium = "1.0.20"
  libssh = "0.11.3"
  libssh2 = "1.11.1"
  libtasn1 = "4.20.0"
  libtiff = "4.7.1"
  libtool = "2.5.4"
  libunistring = "1.4.1"
  libusb = "1.0.29"
  libuv = "1.51.0"
  libvmaf = "3.0.0"
  libvterm = "0.3.3"
  libx11 = "1.8.12"
  libxau = "1.0.12"
  libxcb = "1.17.0"
  libxdmcp = "1.1.5"
  libxext = "1.3.6"
  libxrender = "0.9.12"
  libyaml = "0.2.5"
  libzip = "1.11.4"
  little-cms2 = "2.17"
  llvm = "21.1.5"
  lpeg = "1.1.0"
  lua = "5.4.8"
  luajit = "2.1.1762386122"
  luv = "1.51.0-1"
  lz4 = "1.10.0"
  lzo = "2.10"
  m4 = "1.4.20"
  meta-package-manager = "5.21.0_3"
  mpdecimal = "4.0.1"
  mpfr = "4.2.2"
  msgpack = "6.1.0"
  ncurses = "6.5"
  neovim = "0.11.5"
  nettle = "3.10.2"
  nmap = "7.98"
  npth = "1.8"
  nvm = "0.40.3"
  oniguruma = "6.9.10"
  openexr = "3.4.3"
  openjdk = "25.0.1"
  openjpeg = "2.5.4"
  openjph = "0.25.0"
  "openssl@3" = "3.6.0"
  p11-kit = "0.25.10"
  pcre2 = "10.47"
  pinentry = "1.3.2"
  pixman = "0.46.4"
  pkgconf = "2.5.1"
  python-packaging = "25.0_1"
  python-setuptools = "80.9.0_1"
  "python@3.13" = "3.13.9_1"
  "python@3.14" = "3.14.0_1"
  qq = "64"
  readline = "8.3.1"
  rename = "1.601"
  ripgrep = "15.1.0"
  rpds-py = "0.28.0"
  ruby = "3.4.7"
  rust = "1.91.0"
  shared-mime-info = "2.4_1"
  speexdsp = "1.2.1"
  sqlite = "3.51.0"
  starship = "1.24.0"
  tmux = "3.5a"
  tree = "2.2.1"
  tree-sitter = "0.25.10"
  tree-sitter-cli = "0.25.10"
  unbound = "1.24.1"
  unibilium = "2.1.2"
  utf8proc = "2.11.0"
  vault = "1.20.4"
  vim = "9.1.1850"
  webp = "1.6.0"
  wireshark = "4.6.0_1"
  x265 = "4.1"
  xcodegen = "2.44.1"
  xorgproto = "2024.1"
  xz = "5.8.1"
  yyjson = "0.12.0"
  z3 = "4.15.4"
  zstd = "1.5.7"

