[brew]
  agg = "1.7.0"
  aom = "3.13.1"
  aribb24 = "1.0.4"
  asciinema = "3.0.1"
  bartib = "1.1.0"
  bash = "5.3.9"
  "bash-completion@2" = "2.17.0"
  bat = "0.26.1"
  bfg = "1.15.0"
  brew-file = "10.1.3"
  brotli = "1.2.0"
  c-ares = "1.34.6"
  ca-certificates = "2025-12-02"
  cairo = "1.18.4"
  certifi = "2025.11.12"
  chezmoi = "2.68.1"
  cjson = "1.7.19"
  cmake = "4.2.1"
  dav1d = "1.5.2"
  dos2unix = "7.5.3"
  fastfetch = "2.56.1"
  ffmpeg = "8.0.1"
  flac = "1.5.0"
  fontconfig = "2.17.1"
  freetype = "2.14.1_1"
  frei0r = "2.5.1"
  fribidi = "1.0.16"
  fzf = "0.67.0"
  gawk = "5.3.1"
  gettext = "0.26_1"
  gh = "2.83.2"
  giflib = "5.2.2"
  git-filter-repo = "2.47.0"
  glab = "1.80.4"
  glib = "2.86.3"
  gmp = "6.3.0"
  gnu-getopt = "2.41.3"
  gnu-sed = "4.9"
  gnupg = "2.4.8"
  gnutls = "3.8.11"
  go = "1.25.5"
  graphite2 = "1.3.14"
  harfbuzz = "12.2.0_1"
  highway = "1.3.0"
  "icu4c@77" = "77.1_1"
  "icu4c@78" = "78.1"
  imagemagick = "7.1.2-11"
  imath = "3.2.2"
  jasper = "4.2.8"
  jpeg-turbo = "3.1.3"
  jpeg-xl = "0.11.1_3"
  kanata = "1.10.1"
  keychain = "2.9.8"
  lame = "3.100"
  leptonica = "1.87.0"
  lftp = "4.9.3"
  libarchive = "3.8.4"
  libass = "0.17.4"
  libassuan = "3.0.2"
  libb2 = "0.98.1"
  libbluray = "1.4.0_1"
  libde265 = "1.0.16"
  libdeflate = "1.25"
  libevent = "2.1.12_1"
  libgcrypt = "1.11.2"
  libgit2 = "1.9.2"
  libgpg-error = "1.58"
  libheif = "1.20.2"
  libidn2 = "2.3.8"
  libksba = "1.6.7"
  liblinear = "2.49"
  liblqr = "0.4.3"
  libmaxminddb = "1.12.2"
  libmicrohttpd = "1.0.2"
  libnghttp2 = "1.68.0"
  libnghttp3 = "1.14.0"
  libogg = "1.3.6"
  libomp = "21.1.8"
  libpng = "1.6.53"
  libraw = "0.21.5"
  librist = "0.2.11_1"
  libsamplerate = "0.2.2"
  libsmi = "0.5.0"
  libsndfile = "1.2.2_1"
  libsodium = "1.0.20"
  libsoxr = "0.1.3"
  libssh = "0.11.3"
  libssh2 = "1.11.1"
  libtasn1 = "4.20.0"
  libtiff = "4.7.1"
  libtool = "2.5.4"
  libudfread = "1.2.0"
  libultrahdr = "1.4.0"
  libunibreak = "6.1"
  libunistring = "1.4.1"
  libusb = "1.0.29"
  libuv = "1.51.0"
  libvidstab = "1.1.1"
  libvmaf = "3.0.0"
  libvorbis = "1.3.7"
  libvpx = "1.15.2"
  libvterm = "0.3.3"
  libx11 = "1.8.12"
  libxau = "1.0.12"
  libxcb = "1.17.0"
  libxdmcp = "1.1.5"
  libxext = "1.3.6"
  libxrender = "0.9.12"
  libyaml = "0.2.5"
  libzip = "1.11.4"
  little-cms2 = "2.17"
  llvm = "21.1.8"
  lpeg = "1.1.0"
  lua = "5.4.8"
  luajit = "2.1.1765228720"
  luv = "1.51.0-1"
  lz4 = "1.10.0"
  lzo = "2.10"
  m4 = "1.4.20"
  "mbedtls@3" = "3.6.5"
  meta-package-manager = "6.0.0"
  mpdecimal = "4.0.1"
  mpfr = "4.2.2"
  mpg123 = "1.33.4"
  msgpack = "6.1.0"
  ncurses = "6.5"
  neovim = "0.11.5_1"
  nettle = "3.10.2"
  nmap = "7.98"
  npth = "1.8"
  nvm = "0.40.3"
  oniguruma = "6.9.10"
  opencore-amr = "0.1.6"
  openexr = "3.4.4_1"
  openjdk = "25.0.1"
  openjpeg = "2.5.4"
  openjph = "0.26.0"
  "openssl@3" = "3.6.0"
  opus = "1.6"
  p11-kit = "0.25.10"
  pango = "1.57.0_1"
  pcre2 = "10.47"
  pinentry = "1.3.2"
  pixman = "0.46.4"
  pkgconf = "2.5.1"
  python-packaging = "25.0_1"
  python-setuptools = "80.9.0_1"
  "python@3.13" = "3.13.11"
  "python@3.14" = "3.14.2"
  qq = "64"
  rav1e = "0.8.1"
  readline = "8.3.3"
  rename = "1.601"
  ripgrep = "15.1.0"
  rpds-py = "0.30.0"
  rubberband = "4.0.0"
  ruby = "3.4.8"
  rust = "1.92.0"
  scrcpy = "3.3.4"
  sdl2 = "2.32.10"
  shared-mime-info = "2.4_1"
  snappy = "1.2.2"
  speex = "1.2.1"
  speexdsp = "1.2.1"
  sqlite = "3.51.1"
  srt = "1.5.4"
  starship = "1.24.1"
  svt-av1 = "3.1.2"
  tesseract = "5.5.1_1"
  theora = "1.2.0"
  tmux = "3.6a"
  tree = "2.2.1"
  tree-sitter = "0.26.3"
  tree-sitter-cli = "0.26.3"
  "tree-sitter@0.25" = "0.25.10"
  unbound = "1.24.2"
  unibilium = "2.1.2"
  utf8proc = "2.11.2"
  vault = "1.21.1"
  vim = "9.1.2000"
  webp = "1.6.0"
  wireshark = "4.6.2"
  x264 = "r3222"
  x265 = "4.1"
  xcodegen = "2.44.1"
  xorgproto = "2025.1"
  xvid = "1.3.7"
  xz = "5.8.2"
  yyjson = "0.12.0"
  z3 = "4.15.4"
  zeromq = "4.3.5_2"
  zimg = "3.0.6"
  zstd = "1.5.7"

