[cask]
  1password = "8.11.20"
  1password-cli = "2.32.0"
  adobe-acrobat-reader = "25.001.20937"
  discord = "0.0.369"
  font-inter = "4.1"
  font-jetbrains-mono-nerd-font = "3.4.0"
  ghostty = "1.2.3"
  google-chrome = "143.0.7499.41"
  mouseless = "0.4.3"
  obsidian = "1.10.6"
  raycast = "1.103.10"
  slack = "4.47.65"
  spotify = "1.2.77.358"
  whatsapp = "2.25.36.33"
  wireshark-app = "4.6.2"
  zen = "1.17.12b"
  zoom = "6.6.11.70003"

