[cask]
  1password = "8.11.16"
  1password-cli = "2.32.0"
  adobe-acrobat-reader = "25.001.20756"
  discord = "0.0.365"
  font-inter = "4.1"
  font-jetbrains-mono-nerd-font = "3.4.0"
  ghostty = "1.2.3"
  google-chrome = "142.0.7444.60"
  mouseless = "0.4.3"
  obsidian = "1.9.14"
  qq = "6.9.81_250929_01"
  raycast = "1.103.5"
  slack = "4.46.104"
  spotify = "1.2.75.510"
  whatsapp = "2.25.30.72"
  wireshark-app = "4.6.0"
  zen = "1.17.4b"
  zoom = "6.6.6.67409"

