[cask]
  1password = "8.11.18"
  1password-cli = "2.32.0"
  adobe-acrobat-reader = "25.001.20841"
  discord = "0.0.367"
  font-inter = "4.1"
  font-jetbrains-mono-nerd-font = "3.4.0"
  ghostty = "1.2.3"
  google-chrome = "142.0.7444.176"
  mouseless = "0.4.3"
  obsidian = "1.10.3"
  raycast = "1.103.6"
  slack = "4.47.59"
  spotify = "1.2.76.298"
  whatsapp = "2.25.35.17"
  wireshark-app = "4.6.1"
  zen = "1.17.7b"
  zoom = "6.6.10.69071"

