[cask]
  1password = "8.12.0"
  1password-cli = "2.32.1"
  adobe-acrobat-reader = "25.001.21111"
  alacritty = "0.16.1"
  android-platform-tools = "36.0.2"
  font-inter = "4.1"
  font-jetbrains-mono-nerd-font = "3.4.0"
  ghostty = "1.2.3"
  google-chrome = "144.0.7559.97"
  hiddenbar = "1.9"
  localsend = "1.17.0"
  microsoft-teams = "25290.302.4044.3989"
  mouseless = "0.4.3"
  obsidian = "1.11.5"
  ovim = "latest"
  raycast = "1.104.3"
  slack = "4.47.72"
  wireshark-app = "4.6.3"
  zen = "1.18.1b"

