[cask]
  1password = "8.11.22"
  1password-cli = "2.32.0"
  adobe-acrobat-reader = "25.001.20997"
  alacritty = "0.16.1"
  android-platform-tools = "36.0.0"
  font-inter = "4.1"
  font-jetbrains-mono-nerd-font = "3.4.0"
  ghostty = "1.2.3"
  google-chrome = "143.0.7499.170"
  hiddenbar = "1.9"
  mouseless = "0.4.3"
  obsidian = "1.10.6"
  ovim = "latest"
  raycast = "1.104.1"
  slack = "4.47.72"
  wireshark-app = "4.6.2"
  zen = "1.17.15b"
  zoom = "6.7.0.71075"

